services:
  redis:
    image: redis:8.0-M01
    container_name: youtube-playlist-exporter-redis
    volumes:
      - youtube-playlist-exporter-redis-volume:/data
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - backend-network

  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    container_name: youtube-playlist-downloader-backend
    restart: unless-stopped
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - backend-network
      - reverse-proxy-network

  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    container_name: youtube-playlist-downloader-frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - VITE_API_URL=https://localhost:3443
    networks:
      - reverse-proxy-network

  nginx-backend:
    image: nginx:latest
    container_name: youtube-playlist-downloader-backend-reverse-proxy
    volumes:
      - ./nginx/backend-reverse-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl/dev.pem:/etc/nginx/cert/private_key.pem:ro
      - ./nginx/ssl/cert.pem:/etc/nginx/cert/public_key.pem:ro
      - ./nginx_backend_logs:/var/log/nginx:rw
    ports:
      - 3080:80
      - 3443:443
    links:
     - backend
    networks:
      - reverse-proxy-network

  nginx-frontend:
    image: nginx:latest
    container_name: youtube-playlist-downloader-frontend-reverse-proxy
    volumes:
      - ./nginx/frontend-reverse-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl/dev.pem:/etc/nginx/cert/private_key.pem:ro
      - ./nginx/ssl/cert.pem:/etc/nginx/cert/public_key.pem:ro
      - ./nginx_frontend_logs:/var/log/nginx:rw
    ports:
      - 8080:80
      - 8443:443
    links:
     - frontend
    networks:
      - reverse-proxy-network

volumes:
  youtube-playlist-exporter-redis-volume:

networks:
  backend-network:
  reverse-proxy-network:
