services:
  redis:
    image: redis:8.0-M01
    container_name: youtube-playlist-downloader-redis
    volumes:
      - youtube-playlist-downloader-redis-volume:/data
    command: redis-server --save 60 1 --loglevel warning
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  youtube-playlist-downloader-redis-volume:
